// export 'package:control_asistencia_app/app/view/screen/admin_screens/fingerprintregister.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/home_admin_screen.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/login_admin_screen.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/login_register_tabbar_screen.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/register_admin_screen.dart';
export 'package:control_asistencia_app/app/view/screen/home_screen.dart';
// export 'package:control_asistencia_app/app/view/screen/scan_devices_bluetooth_screen.dart';
export 'package:control_asistencia_app/app/view/screen/settings_screen.dart';
// export 'package:control_asistencia_app/app/view/screen/worker_screens/checkin_method_screens/checkin_fingerprint_screen.dart';
export 'package:control_asistencia_app/app/view/screen/worker_screens/checkin_method_screens/more_options_screen.dart';
export 'package:control_asistencia_app/app/view/screen/worker_screens/home_worker_screeen.dart';
export 'package:control_asistencia_app/firebase_options.dart';
