// export 'package:control_asistencia_app/app/view/screen/admin_screens/fingerprintregister.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/home_admin_screen.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/crud_admin/login_admin_screen.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/login_register_tabbar_screen.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/crud_admin/register_admin_screen.dart';
export 'package:control_asistencia_app/app/view/screen/home_screen.dart';
export 'package:control_asistencia_app/app/view/screen/settings_screen.dart';
export 'package:control_asistencia_app/app/view/screen/worker_screens/home_worker_screeen.dart';
export 'package:control_asistencia_app/prod/firebase_options_prod.dart';
export 'package:control_asistencia_app/app/view/provider/adminprovider.dart';
export 'package:control_asistencia_app/app/view/provider/attendande_provider.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/crud_worker_screens/addworker_screen.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/crud_worker_screens/listworker_screen.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/crud_worker_screens/updateworker_screen.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/listattendance_screen.dart';
export 'package:control_asistencia_app/app/view/screen/admin_screens/perfile_user_screen.dart';
